// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { SimpleAuction$Type } from "./SimpleAuction";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SimpleAuction"]: SimpleAuction$Type;
    ["contracts/SimpleAuction.sol:SimpleAuction"]: SimpleAuction$Type;
  }
}
