// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Counters$Type } from "./Counters";
import { Gaia_Location$Type } from "./Gaia_Location";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Counters"]: Counters$Type;
    ["Gaia_Location"]: Gaia_Location$Type;
    ["contracts/Gaia_Location.sol:Counters"]: Counters$Type;
    ["contracts/Gaia_Location.sol:Gaia_Location"]: Gaia_Location$Type;
  }
}
