// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { GaiaAuction$Type } from "./GaiaAuction";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["GaiaAuction"]: GaiaAuction$Type;
    ["contracts/Gaia_Auction.sol:GaiaAuction"]: GaiaAuction$Type;
  }
}
